name: Pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt  # Use --no-cache-dir here

      - name: Run pylint
        run: |
          pip install --no-cache-dir pylint  # Optional: Use it here as well if pylint is not in requirements.txt
          pylint **/*.py
